import fs from 'node:fs'
const main=fs.readFileSync('src/main.tsx','utf8')
const stage=fs.readFileSync('src/arena-stage.css','utf8')
const fragment=fs.readFileSync('src/arena-blueprint.fragment','utf8')
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'))
function assert(ok,msg){if(!ok)throw new Error(msg)}

assert(main.includes("import './arena-stage.css'"),'Arena 2 coordinate stage is not loaded')
assert(main.includes("import './arena-action.css'"),'Arena 2 action layer is not loaded')
assert(!main.includes('arena-real-phone.css'),'legacy phone geometry remains loaded')
assert(stage.includes('height:100dvh'),'Arena 2 does not fill portrait viewport height')
assert(stage.includes('width:min(100vw,780px)'),'Arena 2 does not use portrait width authority')
assert(fragment.includes('mx2-opponent-hand'),'opponent hand region missing')
assert(fragment.includes('mx2-upper-zone'),'upper zone band missing')
assert(fragment.includes('mx2-vs-left') && fragment.includes('mx2-vs-right'),'side-by-side VS regions missing')
assert(fragment.includes('mx2-command'),'center command region missing')
assert(fragment.includes('mx2-local-hand'),'local five-card hand region missing')
assert(stage.includes('top:14.3%'),'opponent hand coordinate band missing')
assert(stage.includes('top:23.5%'),'upper zone coordinate band missing')
assert(stage.includes('top:35.2%'),'battlefield coordinate band missing')
assert(stage.includes('top:69.2%'),'command coordinate band missing')
assert(stage.includes('bottom:1.2%'),'local hand is not anchored at bottom')
assert(!pkg.scripts.build.includes('patch-single-fight.mjs'),'obsolete FIGHT patch remains in build')
assert(!pkg.scripts.build.includes('dump-arena-source.mjs'),'diagnostic Arena dump remains active')
console.log('PASS Arena 2 viewport uses one full-height portrait map with new geometry')
