import fs from 'node:fs'
const main=fs.readFileSync('src/main.tsx','utf8')
const fragment=fs.readFileSync('src/arena-blueprint.fragment','utf8')
const stage=fs.readFileSync('src/arena-stage.css','utf8')
const runtime=fs.readFileSync('src/arena-stage.ts','utf8')
const app=fs.readFileSync('src/App.tsx','utf8')
const must=(ok,msg)=>{if(!ok)throw new Error(msg)}
must(main.includes("import './arena-stage.css'"),'Arena MX3 stylesheet not imported')
must(!main.includes('arena-action.css')&&!main.includes('arena-overlay.css'),'Arena MX3 must use one stylesheet')
must(main.includes("import './arena-stage.ts'"),'Arena MX3 runtime missing')
must(fragment.includes('mx3-canvas'),'Arena MX3 fixed canvas missing')
must((fragment.match(/mx3-vs/g)||[]).length>=2,'two VS frames required')
must((fragment.match(/mx3-effects/g)||[]).length>=2,'two Effect rails required')
must(fragment.includes('Array.from({ length: 5 }'),'five-slot Effect structure missing')
must(fragment.includes('mx3-local-hand')&&fragment.includes('mx3-opponent-hand'),'hand regions missing')
must(fragment.includes('mx3-big-counter')&&fragment.includes('mx3-master-counter'),'new counters missing')
must(fragment.includes('setPileView')&&fragment.includes('setFocusedCard'),'handlers missing')
must(stage.includes('width:780px')&&stage.includes('height:1110px'),'fixed 780x1110 canvas contract missing')
must(stage.includes('width:210px!important;height:280px!important'),'210x280 VS frame contract missing')
must(stage.includes('width:200px!important;height:280px!important'),'VS card must render at exact 5:7 ratio')
must(stage.includes('flex:0 0 90px!important')&&stage.includes('width:64px!important;height:90px!important'),'Effect rail must use side height while keeping card art near 5:7')
must(stage.includes('mx3VSPhase')&&stage.includes('mx3PurplePhase')&&stage.includes('mx3GoldPhase'),'phase animations missing')
must(runtime.includes('window.innerWidth / WIDTH')&&runtime.includes('window.innerHeight / HEIGHT'),'uniform runtime scaling missing')
must(runtime.includes("shell.classList.add('mx3-stage')"),'Arena MX3 runtime marker missing')
must(runtime.includes("outcome.textContent = winnerName === localName ? 'MENANG!' : 'KALAH'"),'winner/loser result split missing')
must(app.includes('mx3-canvas'),'generated App does not contain Arena MX3')
must(!app.includes('<div className="arena-wrap">'),'legacy board survived')
console.log('PASS Arena MX3 proportions, phase animation, and MENANG/KALAH result contract')
