import fs from 'node:fs'
const audio = fs.readFileSync('src/audio.ts','utf8')
const assets = fs.readFileSync('src/audio-assets.ts','utf8')
const vercel = JSON.parse(fs.readFileSync('vercel.json','utf8'))
const must = (ok, msg) => { if (!ok) throw new Error(msg) }

must(assets.includes("'/audio/arena/arena-c2-v1.opus'"), 'arena C2 asset missing')
must(assets.includes("'/audio/arena/arena-c3-v1.opus'"), 'arena C3 asset missing')
must(assets.includes('ARENA_TRACKS'), 'extensible arena track pool missing')
must(audio.includes('COIN_TOSS_GAIN = 1.0'), 'VS intro music gain missing')
must(audio.includes('ARENA_GAIN = 0.88'), 'arena background gain missing')
must(audio.includes('pickArenaTrack'), 'one-track-per-match selector missing')
must(audio.includes('audio.loop = true'), 'selected arena track must loop')
must(audio.includes('ARENA_BAG_KEY'), 'non-repeating arena shuffle bag missing')
must(audio.includes('fadeInMusic'), 'arena fade-in missing')
must(audio.includes('duckArenaMusic'), 'arena ducking missing')
must(audio.includes('SFX_DUCK_GAIN = 0.56'), 'critical SFX duck target must be about -5 dB')
must(audio.includes('SFX_LIGHT_DUCK_GAIN = 0.72'), 'light SFX duck target missing')
must(audio.includes('SFX_BASE_GAIN = 0.9'), 'audible normalized SFX playback gain missing')
must(audio.includes('card: 0.25'), 'card-selection cue must be substantially reduced')
must(audio.includes('draw: 1.25'), 'draw cue priority gain missing')
must(audio.includes('vsEnter: 1.25'), 'VS-entry cue priority gain missing')
must(audio.includes('attack: 0.72'), 'attack cue must be reduced below the other priority cues')
must(audio.includes('zonX: 1.15'), 'Zon X cue priority gain missing')
must(assets.includes("export const LOBBY_TRACK = '/audio/replacements/lobby.opus'"), 'single replacement lobby track missing')
must(audio.includes('new Audio(LOBBY_TRACK)'), 'lobby must use only replacement track')
for (const name of ['card-selected','card-draw','effect-enter-field','card-enter-vs','card-attacking','card-destroyed','card-goes-to-zon-x','prompt-needed']) must(assets.includes(`/audio/replacements/${name}.opus`), `replacement audio missing: ${name}`)
must(assets.includes("winLose: '/audio/replacements/win-lose-screen.opus'"), 'win/lose result music mapping missing')
must(!assets.includes('player-win.opus'), 'legacy player-win mapping must be removed')
must(assets.includes("'vsEnter'"), 'dedicated VS-entry SFX type missing')
must(audio.includes("kind === 'ENTER_VS') this.playSfx('vsEnter')"), 'dedicated VS-entry playback missing')
must(audio.includes("else if (kind === 'SUPPORT') this.playSfx('enter')"), 'Effect entry SFX trigger missing')
must(audio.includes("else if (kind === 'CAPTURE') this.playSfx('zonX')"), 'Zon X motion trigger missing')
must(audio.includes('window.setInterval(() => this.syncArenaStateSfx(), 180)'), 'Arena state SFX must poll independently of DOM mutation batching')
must(audio.includes("deckCount < this.lastArenaDeckCount) this.playSfx('draw')"), 'draw fallback must react to Master Deck count dropping')
must(audio.includes('if (!this.unlocked && cardId) return'), 'occupied VS identity must remain pending until audio is unlocked')
must(audio.includes("previous !== cardId && cardId && performance.now() - this.lastVsEntryGestureAt > 1200) this.playSfx('vsEnter')"), 'VS-entry identity fallback must fire after card identity changes unless the direct gesture just played it')
must(audio.includes("document.addEventListener('pointerdown', this.onVsEntryPointerDown, true)"), 'VS-entry direct playback must be bound to pointerdown user activation')
must(audio.includes("this.lastVsEntryGestureAt = performance.now()"), 'VS-entry pointerdown playback must timestamp direct playback for de-duplication')
must(!audio.includes("kind === 'ENTER_VS' || kind === 'SUPPORT'"), 'Effect-enter-field SFX must not play for VS placement')
must(assets.includes('SFX_REV'), 'replacement SFX must be cache-busted')
must(!fs.existsSync('public/audio/replacements/fight.opus'), 'FIGHT audio file must not exist in production tree')
must(!assets.includes('arena-appear.opus'), 'Arena-entry audio path must stay removed')
must(!assets.includes('arenaAppear'), 'Arena-entry SFX type must be removed')
must(!audio.includes('arenaAppear'), 'Arena-entry playback trigger must be removed')
must(!assets.includes('/audio/replacements/fight.opus'), 'FIGHT announcer asset mapping must be removed')
must(!assets.includes("'fight'"), 'FIGHT announcer SFX type must be removed')
must(audio.includes("if (kind === 'DRAW') this.playSfx('draw')"), 'draw SFX trigger missing')
must(audio.includes("playSfx('zonX')"), 'Zon X SFX trigger missing')
must(audio.includes("playSfx('prompt')"), 'prompt SFX trigger missing')
must(audio.includes('syncPromptSfx'), 'prompt audio must be synchronized from the live prompt state')
must(audio.includes(".mx3-phase-prompt strong") && audio.includes('.mx3-target-selection-title'), 'prompt audio must read only actual prompt UI')
must(audio.includes('if (prompt === this.lastPrompt) return'), 'same live prompt must never replay from unrelated DOM mutations')
must(audio.includes("if (!prompt) { this.lastPrompt = ''; return }"), 'prompt latch must reset only when no prompt is active')
must(!audio.includes('lastPromptAt'), 'time-based prompt debounce must be removed')
must(audio.includes('private resultAudio'), 'result music must be preloaded instead of allocated at game-over')
must(audio.includes('preloadResultMusic'), 'result music preload routine missing')
must(audio.includes('this.resultAudio.currentTime = 0'), 'result music must restart immediately from its cached element')
must(audio.includes('playResultMusic'), 'result-screen one-shot music handler missing')
must(audio.includes('loop = false'), 'win/lose screen music must never loop')
must(audio.includes("document.querySelector('.mx3-canvas.phase-game_over')"), 'win/lose result music must be gated by GAME_OVER phase')
must(!audio.includes("/PERLAWANAN\\s+TAMAT|MENANG!?|KALAH|YOU\\s+WIN|YOU\\s+LOSE|ANDA\\s+MENANG/.test(text)"), 'mid-match MENANG/KALAH text must not trigger result music')
must(!audio.includes("playSfx('win')"), 'legacy player-win SFX trigger must be removed')
must(!/\bFIGHT\b/.test(audio), 'FIGHT announcer detection must be removed')
must(!assets.includes('VOICE_ASSETS'), 'legacy announcer asset map must stay removed')
must(!audio.includes('playVoice'), 'legacy announcer playback must stay removed')
const arenaHeader = (vercel.headers ?? []).find((entry) => String(entry.source ?? '').startsWith('/audio/arena/'))
must(Boolean(arenaHeader), 'arena immutable cache route missing')
must(JSON.stringify(arenaHeader).includes('max-age=31536000, immutable'), 'arena immutable cache policy missing')
console.log('PASS arena audio: pointerdown VS-entry authority, de-duplicated identity fallback, prompt SFX, and Arena mix contracts remain intact')
