import fs from 'node:fs'
const app=fs.readFileSync('src/App.tsx','utf8')
const css=fs.readFileSync('src/arena-stage.css','utf8')
const main=fs.readFileSync('src/main.tsx','utf8')
const must=(ok,msg)=>{if(!ok)throw new Error(msg)}
const duelStart=app.indexOf('<section className="duel-shell">')
must(duelStart>=0,'duel shell missing')
const duel=app.slice(duelStart)
must(!main.includes('arena-overlay.css'),'separate overlay stylesheet must not be loaded')
must(duel.includes('mx3-card-overlay'),'Arena MX3 selected-card overlay missing')
must(duel.includes('mx3-card-overlay-panel'),'Arena MX3 text panel missing')
must(duel.includes("setVS(bottomPlayer, focusedCard.id, 'ATK')"),'ATK placement action missing')
must(duel.includes("setVS(bottomPlayer, focusedCard.id, 'DEF')"),'DEF placement action missing')
must(duel.includes('playEffect(bottomPlayer, focusedCard.id)'),'Effect placement action missing')
must(duel.includes('setFocusedCard(null)'),'overlay close action missing')
must(css.includes('.mx3-card-overlay-panel'),'overlay geometry missing from sole Arena stylesheet')
const selectedStart=duel.indexOf('{focusedCard && passToPlayer === null')
must(selectedStart>=0,'selected-card render path missing')
const selectedWindow=duel.slice(selectedStart,selectedStart+1800)
must(selectedWindow.includes('mx3-card-overlay'),'selected card does not route to MX3 overlay')
must(selectedWindow.includes('mx3-card-overlay-effect'),'selected-card effect text missing')
must(selectedWindow.includes('mx3-card-overlay-stats'),'selected-card text stats missing')
must(!selectedWindow.includes('mx3-card-overlay-preview'),'selected-card image preview must not exist')
must(!selectedWindow.includes('<CardView card={focusedCard}'),'selected-card overlay must be text-only')
must(!selectedWindow.includes('card-focus-overlay'),'selected card still routes to legacy full-screen overlay')
console.log('PASS Arena MX3 selected-card overlay is text-only and exposes authoritative actions')
