import fs from 'node:fs'
const main=fs.readFileSync('src/main.tsx','utf8')
const fragment=fs.readFileSync('src/arena-blueprint.fragment','utf8')
const stage=fs.readFileSync('src/arena-stage.css','utf8')
const runtime=fs.readFileSync('src/arena-stage.ts','utf8')
const app=fs.readFileSync('src/App.tsx','utf8')
const must=(ok,msg)=>{if(!ok)throw new Error(msg)}
must(main.includes("import './arena-stage.css'"),'Arena MX3 stylesheet not imported')
must(!main.includes('arena-action.css')&&!main.includes('arena-overlay.css'),'Arena MX3 must use one authoritative stage stylesheet plus presentation layers')
must(main.includes("import './arena-stage.ts'"),'Arena MX3 runtime missing')
must(fragment.includes('mx3-canvas'),'Arena MX3 fixed canvas missing')
must(fragment.includes('mx3-center-vs'),'central VS combat identity missing')
must((fragment.match(/mx3-vs/g)||[]).length>=2,'two VS frames required')
must((fragment.match(/mx3-effects/g)||[]).length>=2,'two Effect rails required')
must(fragment.includes('Array.from({ length: 5 }'),'five-slot Effect structure missing')
must(fragment.includes('mx3-local-hand')&&fragment.includes('mx3-opponent-hand'),'hand regions missing')
must(fragment.includes('mx3-big-counter')&&fragment.includes('mx3-master-counter'),'new counters missing')
must(fragment.includes('setPileView')&&fragment.includes('setFocusedCard'),'handlers missing')
must(stage.includes('width:780px')&&stage.includes('height:1110px'),'fixed 780x1110 canvas contract missing')
must(stage.includes('width:210px!important;height:280px!important'),'210x280 VS frame contract missing')
must(stage.includes('width:200px!important;height:280px!important'),'VS card must render at exact 5:7 ratio')
must(stage.includes('flex:0 0 98px!important')&&stage.includes('width:66px!important;height:92px!important'),'Effect rail must fill side height while keeping portrait card art')
must(stage.includes('mx3VSPhase')&&stage.includes('mx3PurplePhase')&&stage.includes('mx3GoldPhase'),'phase animations missing')
must(stage.includes('mx3MotionVS')&&stage.includes('mx3MotionEffect')&&stage.includes('mx3ImpactText'),'card travel/combat animation system missing')
must(runtime.includes('viewportWidth / WIDTH')&&runtime.includes('viewportHeight / HEIGHT')&&runtime.includes('Math.min('),'uniform runtime scaling missing')
must(runtime.includes("shell.classList.add('mx3-stage')"),'Arena MX3 runtime marker missing')
must(runtime.includes("const nextOutcome = isLoss ? 'KALAH' : 'MENANG!'"),'winner/loser result split missing')
must(runtime.includes('panel.dataset.mx3WinnerName'),'winner identity persistence missing')
must(runtime.includes("if (outcome.textContent !== nextOutcome) outcome.textContent = nextOutcome"),'result copy must not recursively rewrite identical text inside MutationObserver')
must(app.includes('CARD_INFO[focusedCard.id]?.effect'),'selected-card overlay must use authoritative card info')
must(app.includes('mx3-canvas'),'generated App does not contain Arena MX3')
must(!app.includes('<div className="arena-wrap">'),'legacy board survived')
console.log('PASS Arena MX3 proportions, responsive uniform scaling, central VS, card info, motion system, and MENANG/KALAH contract')
