import fs from 'node:fs'

const must=(ok,msg)=>{if(!ok)throw new Error(msg)}
const files=['Arena3DRoot.tsx','Arena3DScene.tsx','Arena3DTable.tsx','Arena3DCard.tsx','Arena3DZones.tsx','Arena3DHUD.tsx','arena3d.css']
for(const file of files)must(fs.existsSync(`src/game/arena3d/${file}`),`missing Gate 1 3D file: ${file}`)
const root=fs.readFileSync('src/game/arena3d/Arena3DRoot.tsx','utf8')
const scene=fs.readFileSync('src/game/arena3d/Arena3DScene.tsx','utf8')
const card=fs.readFileSync('src/game/arena3d/Arena3DCard.tsx','utf8')
const hud=fs.readFileSync('src/game/arena3d/Arena3DHUD.tsx','utf8')
const css=fs.readFileSync('src/game/arena3d/arena3d.css','utf8')
const camera=fs.readFileSync('src/game/arena3d/Arena3DCameraRig.tsx','utf8')
const boot=fs.readFileSync('src/game/arena3d/Arena3DBoot.tsx','utf8')
must(root.includes('Canvas'),'3D root must own a React Three Fiber Canvas')
must(scene.includes('PerspectiveCamera'),'3D scene must use perspective camera framing')
must(card.includes('useTexture'),'3D cards must use real game texture URLs')
must(card.includes('card.actionId'),'3D card clicks must honor primary authoritative actions')
must(card.includes('onPointerUp'),'3D card activation must use release/tap semantics instead of pointer-down firing')
must(card.includes('Math.hypot'),'3D card taps must reject drag movement before activating')
must(hud.includes('state.prompt'),'HUD must show the current gameplay prompt')
must(hud.includes('state.legalActions'),'HUD must render authoritative legal commands')
must(hud.includes('requestFullscreen'),'HUD must expose fullscreen control')
must(hud.includes('mx3d-mobile-hand'),'HUD must expose a coarse-pointer card-selection fallback')
must(hud.includes('onCardSelect'),'mobile card fallback must reach the same card action chooser')
must(css.includes('(pointer:coarse)'),'mobile hand fallback must activate for coarse pointers')
must(css.includes('touch-action:none'),'3D canvas must own touch gestures consistently')
must(camera.includes('size.width/size.height'),'3D camera must adapt framing to viewport aspect')
must(boot.includes("inset:'0'"),'3D host must size from fixed inset rather than fragile viewport units')
must(!boot.includes("height:'100dvh'"),'3D host must not depend on dynamic viewport-height support')
console.log('PASS Gate 1 Mega X perspective 3D arena shell contract')
