import fs from 'node:fs'
const audio = fs.readFileSync('src/audio.ts','utf8')
const assets = fs.readFileSync('src/audio-assets.ts','utf8')
const vercel = JSON.parse(fs.readFileSync('vercel.json','utf8'))
const must = (ok, msg) => { if (!ok) throw new Error(msg) }

must(assets.includes("'/audio/arena/arena-c2-v1.opus'"), 'arena C2 asset missing')
must(assets.includes("'/audio/arena/arena-c3-v1.opus'"), 'arena C3 asset missing')
must(assets.includes('ARENA_TRACKS'), 'extensible arena track pool missing')
must(audio.includes('ARENA_GAIN = 0.58'), 'arena background gain missing')
must(audio.includes('pickArenaTrack'), 'one-track-per-match selector missing')
must(audio.includes('audio.loop = true'), 'selected arena track must loop')
must(audio.includes('ARENA_BAG_KEY'), 'non-repeating arena shuffle bag missing')
must(audio.includes('fadeInMusic'), 'arena fade-in missing')
must(audio.includes('duckArenaMusic'), 'arena ducking missing')
must(audio.includes('SFX_DUCK_GAIN = 0.56'), 'critical SFX duck target must be about -5 dB')
must(audio.includes('SFX_LIGHT_DUCK_GAIN = 0.72'), 'light SFX duck target missing')
must(audio.includes('SFX_BASE_GAIN = 0.9'), 'audible normalized SFX playback gain missing')
must(audio.includes('draw: 1.25'), 'draw cue priority gain missing')
must(audio.includes('vsEnter: 1.25'), 'VS-entry cue priority gain missing')
must(audio.includes('attack: 1.2'), 'attack cue priority gain missing')
must(assets.includes("export const LOBBY_TRACK = '/audio/replacements/lobby.opus'"), 'single replacement lobby track missing')
must(audio.includes('new Audio(LOBBY_TRACK)'), 'lobby must use only replacement track')
for (const name of ['card-selected','card-draw','effect-enter-field','card-enter-vs','card-attacking','card-destroyed','card-goes-to-zon-x','prompt-needed']) must(assets.includes(`/audio/replacements/${name}.opus`), `replacement audio missing: ${name}`)
must(assets.includes("winLose: '/audio/replacements/win-lose-screen.opus'"), 'win/lose result music mapping missing')
must(!assets.includes('player-win.opus'), 'legacy player-win mapping must be removed')
must(assets.includes("'vsEnter'"), 'dedicated VS-entry SFX type missing')
must(audio.includes("kind === 'ENTER_VS') this.playSfx('vsEnter')"), 'dedicated VS-entry playback missing')
must(audio.includes("else if (kind === 'SUPPORT') this.playSfx('enter')"), 'Effect entry SFX trigger missing')
must(!audio.includes("kind === 'ENTER_VS' || kind === 'SUPPORT'"), 'Effect-enter-field SFX must not play for VS placement')
must(assets.includes('SFX_REV'), 'replacement SFX must be cache-busted')
must(!fs.existsSync('public/audio/replacements/fight.opus'), 'FIGHT audio file must not exist in production tree')
must(!assets.includes('arena-appear.opus'), 'Arena-entry audio path must be removed until the verified non-announcer asset is restored')
must(!assets.includes('arenaAppear'), 'Arena-entry SFX type must be removed')
must(!audio.includes('arenaAppear'), 'Arena-entry playback trigger must be removed')
must(!assets.includes('/audio/replacements/fight.opus'), 'FIGHT announcer asset mapping must be removed')
must(!assets.includes("'fight'"), 'FIGHT announcer SFX type must be removed')
must(audio.includes("if (kind === 'DRAW') this.playSfx('draw')"), 'draw SFX trigger missing')
must(audio.includes("playSfx('zonX')"), 'Zon X SFX trigger missing')
must(audio.includes("playSfx('prompt')"), 'prompt SFX trigger missing')
must(audio.includes('playResultMusic'), 'result-screen one-shot music handler missing')
must(audio.includes('audio.loop = false'), 'win/lose screen music must never loop')
must(/MENANG|KALAH|YOU WIN|YOU LOSE/.test(audio), 'both win and lose result states must trigger result music')
must(!audio.includes("playSfx('win')"), 'legacy player-win SFX trigger must be removed')
must(!/\bFIGHT\b/.test(audio), 'FIGHT announcer detection must be removed')
must(!assets.includes('VOICE_ASSETS'), 'legacy announcer asset map must stay removed')
must(!audio.includes('playVoice'), 'legacy announcer playback must stay removed')
const arenaHeader = (vercel.headers ?? []).find((entry) => String(entry.source ?? '').startsWith('/audio/arena/'))
must(Boolean(arenaHeader), 'arena immutable cache route missing')
must(JSON.stringify(arenaHeader).includes('max-age=31536000, immutable'), 'arena immutable cache policy missing')
console.log('PASS arena audio: audible priority SFX, controlled music ducking, dedicated VS-entry, one-shot win/lose music, no legacy player-win/FIGHT path')
