import fs from 'node:fs'
const app=fs.readFileSync('src/App.tsx','utf8')
const v24=fs.readFileSync('src/V24.css','utf8')
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'))
function assert(ok,msg){if(!ok)throw new Error(msg)}
assert(app.includes('mx-responsive-discard-title'),'discard chooser responsive hook missing')
assert(app.includes('mx-responsive-vs-title'),'VS chooser responsive hook missing')
assert(v24.includes('/* MEGA-X unified arena responsive system */'),'unified arena viewport system missing')
assert(pkg.scripts.build.includes('patch-arena-responsive-system.mjs'),'unified arena system is not built')
assert(!pkg.scripts.build.includes('patch-responsive-arena.mjs'),'legacy responsive arena patch remains active')
assert(!pkg.scripts.build.includes('patch-mobile-arena-v2.mjs'),'legacy mobile arena patch remains active')
assert(v24.includes('.duel-shell .mx-quit-match{position:fixed!important'),'QUIT/SURRENDER is not viewport-pinned')
assert(v24.includes('max-height:calc(100dvh - 126px)!important;overflow:auto!important;-webkit-overflow-scrolling:touch!important'),'chooser content does not have touch scrolling fallback')
assert(v24.includes('.duel-shell .digital-card{aspect-ratio:var(--mx-card-ratio)!important'),'card artwork does not share the authoritative ratio')
assert(v24.includes('.duel-shell .battlefield{') && v24.includes('grid-row:3!important'),'battlefield does not own the middle responsive row')
assert(v24.includes('.duel-shell .hand-area{') && v24.includes('grid-row:4!important'),'hand does not own its reserved responsive row')
assert(v24.includes('@container mx-arena (max-aspect-ratio: 3/4)'),'portrait layout contract missing')
assert(v24.includes('@container mx-arena (min-aspect-ratio: 4/3)'),'wide layout contract missing')
assert(!v24.includes('.mega-coin{will-change:transform!important;contain:layout paint style!important;transform:translateZ(0)}'),'mobile coin transform override still suppresses original keyframes')
assert(!v24.includes('margin-left:-26px!important'),'fixed phone hand overlap still active')
assert(!v24.includes('transform:scale(.72)!important'),'fixed phone HUD scaling still active')
console.log('PASS Arena uses one responsive geometry contract with unobstructed coin keyframes')
