import fs from 'node:fs'

const main = fs.readFileSync('src/main.tsx','utf8')
const stage = fs.readFileSync('src/arena-stage.css','utf8')
const action = fs.readFileSync('src/arena-action.css','utf8')
const runtime = fs.readFileSync('src/arena-stage.ts','utf8')
const cards = fs.readFileSync('src/arena-card-info.ts','utf8')
const app = fs.readFileSync('src/App.tsx','utf8')
const must = (ok,msg) => { if(!ok) throw new Error(msg) }

must(main.includes("import './arena-stage.css'"), 'portrait Arena CSS is not imported')
must(main.includes("import './arena-action.css'"), 'Arena action motion CSS is not imported')
must(main.includes("import './arena-stage.ts'"), 'portrait Arena runtime is not imported')
must(!main.includes("arena-real-phone.css"), 'legacy phone geometry is still imported')
must(stage.includes('authoritative portrait blueprint 780 x 1110'), 'portrait blueprint contract missing')
must(stage.includes('.mx-arena-board'), 'new Arena board geometry missing')
must(stage.includes('.mx-side-left .mx-effect-column'), 'left effect rack missing')
must(stage.includes('.mx-side-right .mx-effect-column'), 'right effect rack missing')
must(stage.includes('grid-template-rows:repeat(5'), 'five protected Effect slots missing')
must(app.includes('className="mx-position-strip"'), 'POSISI KAD structural rows missing')
must((app.match(/mx-position-strip/g) || []).length >= 2, 'both VS position rows are required')
must(app.includes('mx-vs-module'), 'new VS modules missing')
must(!app.includes('<div className="arena-wrap">'), 'legacy arena-wrap survived structural rebuild')
must(!app.includes('mx-blueprint-stage'), 'legacy wrapper survived structural rebuild')
must(stage.includes('.mx-card-inspector'), 'card inspector styling missing')
must(action.includes('.mx-card-inspector__actions'), 'inspector action row missing')
must(action.includes('mxPhaseGlow'), 'phase-driven glow missing')
must(action.includes('mxZoneScoreFlash'), 'Zon X score flash missing')
must(action.includes('mxTargetPulse'), 'target pulse missing')
must(action.includes('mxPlayConfirm'), 'play confirmation animation missing')
must(runtime.includes('CARD_INFO'), 'inspector is not backed by card data')
must(runtime.includes('data-mx-play'), 'overlay PLAY action missing')
must(runtime.includes('stopImmediatePropagation'), 'hand tap is not separated from play confirmation')
must(runtime.includes('mx-score-changed'), 'score-change feedback missing')
must((cards.match(/\bid:\d+/g) || []).length === 30, 'card inspector database must contain 30 cards')

console.log('PASS portrait Arena: real rebuilt board structure, protected zones and existing interaction feedback')
