import fs from 'node:fs'
const app=fs.readFileSync('src/App.tsx','utf8')
const v24=fs.readFileSync('src/V24.css','utf8')
function assert(ok,msg){if(!ok)throw new Error(msg)}
assert(app.includes('mx-responsive-discard-title'),'discard chooser responsive hook missing')
assert(app.includes('mx-responsive-vs-title'),'VS chooser responsive hook missing')
assert(v24.includes('/* Responsive arena viewport contract */'),'responsive arena viewport patch missing')
assert(v24.includes('/* Authoritative phone-first arena contract */'),'phone-first arena contract missing')
assert(v24.includes('.duel-shell .mx-quit-match{position:fixed!important'),'QUIT/SURRENDER is not viewport-pinned')
assert(v24.includes('max-height:calc(100dvh - 24px)!important'),'chooser panels are not bounded to viewport')
assert(v24.includes('.duel-shell .hand-card-wrap .digital-card{display:block!important;width:100%!important'),'hand artwork can still overflow its wrapper')
assert(v24.includes('.duel-shell [class]:has(> .mx-responsive-vs-title)>div'),'VS chooser content does not have its own viewport scroll region')
assert(v24.includes('.duel-shell [class]:has(> .mx-responsive-discard-title)>div'),'discard chooser content does not have its own viewport scroll region')
assert(v24.includes('.duel-shell .vs-inspect-button{width:100%!important;max-width:100%!important'),'mobile VS cards can still force overlap outside their grid cell')
assert(v24.includes('.duel-shell .player-hand .hand-card-wrap{height:176px!important'),'phone hand cards are still desktop-small')
assert(v24.includes('.duel-shell .arena{width:100%!important;height:100%!important;max-width:100%!important;aspect-ratio:auto!important'),'phone arena is still constrained by desktop 16:9 geometry')
assert(!v24.includes('.mega-coin{will-change:transform!important;contain:layout paint style!important;transform:translateZ(0)}'),'mobile coin transform override still suppresses original keyframes')
assert(v24.includes('overflow:auto!important;-webkit-overflow-scrolling:touch!important'),'chooser content does not have touch scrolling fallback')
console.log('PASS arena phone layout keeps VS cards separated, hand readable, and coin keyframes unobstructed')
