import fs from 'node:fs'
const app=fs.readFileSync('src/App.tsx','utf8')
const audio=fs.readFileSync('src/audio.ts','utf8')
const assets=fs.readFileSync('src/audio-assets.ts','utf8')
const stage=fs.readFileSync('src/arena-stage.css','utf8')
const fragment=fs.readFileSync('src/arena-blueprint.fragment','utf8')
const main=fs.readFileSync('src/main.tsx','utf8')
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'))
const must=(ok,msg)=>{if(!ok)throw new Error(msg)}
must(pkg.scripts.build.includes('patch-production-jank-hotfix.mjs'),'production motion/audio hotfix missing')
must(!pkg.scripts.build.includes('patch-single-fight.mjs'),'obsolete FIGHT patch remains')
must(stage.includes('MEGA-X ARENA MX3'),'Arena MX3 stage is not authoritative')
must(fragment.includes('mx3-canvas')&&fragment.includes('mx3-local-hand'),'Arena MX3 fragment missing')
must(main.includes("import './arena-stage.css'")&&!main.includes('arena-action.css')&&!main.includes('arena-overlay.css'),'Arena MX3 must have one Arena stylesheet')
const requiredAssets=["card: '/audio/replacements/card-selected.opus'","draw: '/audio/replacements/card-draw.opus'","enter: '/audio/replacements/effect-enter-field.opus'","attack: '/audio/replacements/card-attacking.opus'","destroy: '/audio/replacements/card-destroyed.opus'","zonX: '/audio/replacements/card-goes-to-zon-x.opus'","prompt: '/audio/replacements/prompt-needed.opus'","arenaAppear: '/audio/replacements/arena-appear.opus'","win: '/audio/replacements/player-win.opus'"]
for(const asset of requiredAssets) must(assets.includes(asset),`replacement audio asset missing: ${asset}`)
must(!assets.includes('fight.opus'),'FIGHT announcer asset mapping remains')
must(!audio.includes("playSfx('fight')"),'FIGHT announcer playback remains')
must(!audio.includes('playVoice'),'legacy announcer playback remains')
must(app.includes("new CustomEvent('mega-x:motion'"),'motion state does not dispatch gameplay audio events')
must(app.includes('CONFIRM DISCARD')&&app.includes('selectedDiscardIds'),'Spudur discard interaction missing')
console.log('PASS Arena MX3 audit: fixed diagram presentation, one stylesheet, replacement SFX, no FIGHT announcer')
