import fs from 'node:fs'

const main = fs.readFileSync('src/main.tsx','utf8')
const app = fs.existsSync('src/App.tsx') ? fs.readFileSync('src/App.tsx','utf8') : ''
const patch = fs.readFileSync('scripts/patch-arena-usability.mjs','utf8')
const css = fs.readFileSync('src/arena-usability.css','utf8')
const stage = fs.readFileSync('src/arena-stage.css','utf8')
const bridge = fs.readFileSync('src/arena-usability.ts','utf8')
const audio = fs.readFileSync('src/audio.ts','utf8')

const must = (ok,msg) => { if (!ok) throw new Error(msg) }
const builtOrPatched = (needle) => app.includes(needle) || patch.includes(needle)

must(main.includes("import './arena-usability.css'"), 'Arena usability CSS import missing')
must(main.includes("import './arena-usability.ts'"), 'Arena usability runtime import missing')
must(builtOrPatched("mega-x:audio-toggle-request"), 'Arena AUDIO button is not wired to audio-panel request')
must(builtOrPatched('>AUDIO</button>'), 'Arena AUDIO button must be a settings tab, not an ON/OFF mute button')
must(builtOrPatched("mega-x:arena-feedback"), 'Arena STA feedback event missing')
must(builtOrPatched('STA HABIS'), 'Arena exhausted-STA warning copy missing')
must(css.includes('backdrop-filter:blur(') || css.includes('backdrop-filter: blur('), 'Arena prompt glass blur missing')
must(css.includes('.mx3-phase-prompt button') && css.includes('min-height:52px'), 'Arena prompt touch target is too small')
must(css.includes('min-height:88px'), 'Arena narrow-screen prompt touch target is not enlarged')
must(css.includes('.mx3-arena-toast'), 'Arena feedback toast styling missing')
must(bridge.includes("addEventListener(AUDIO_REQUEST"), 'Arena audio bridge listener missing')
must(bridge.includes("addEventListener(FEEDBACK_EVENT"), 'Arena feedback toast listener missing')
must(bridge.includes("[data-audio-toggle]"), 'Arena AUDIO tab does not open existing audio settings panel')
must(!bridge.includes("mute.click()"), 'Arena AUDIO tab must not directly toggle mute')
must(bridge.includes('audioUiSyncQueued'),'Arena audio UI observer must coalesce mutation callbacks')
must(bridge.includes("attributeFilter: ['class', 'hidden']"),'Arena audio UI observer must stay scoped to relevant attributes')
must(audio.includes('[data-audio-music]') && audio.includes('[data-audio-sfx]') && audio.includes('[data-audio-mute]'), 'audio panel must expose MUSIC, SFX and MUTE controls')
must(!stage.includes('#mx-audio-controls{display:none!important}'), 'Arena must not hide the existing audio controls root')
must(stage.includes('[data-audio-panel][hidden]') && stage.includes('[data-audio-panel]:not([hidden])'), 'Arena audio panel visibility states missing')
must(stage.includes('.mx3-local-hand') && stage.includes('top:895px!important'), 'local hand was not moved down to reduce top-area crowding')
must(bridge.includes('PILIH KAD UNTUK DIBUANG'), 'Android discard-selection dialog is not tagged for viewport safety')
must(bridge.includes('mx3-discard-selection-panel'), 'Android discard-selection dialog is not distinguished from normal target selection')
must(css.includes('.mx3-target-selection-overlay') && css.includes('position:fixed!important') && css.includes('inset:0!important'), 'Android selection overlay is not pinned to the visible dynamic viewport')
must(css.includes('height:100dvh!important'), 'Android selection overlay does not own the visible dynamic viewport height')
must(css.includes('.mx3-discard-selection-panel') && css.includes('max-height:24dvh!important') && css.includes('max-width:min(44vw,180px)!important'), 'Android discard cards are still too large to track selection count')

console.log('PASS Arena usability: functional AUDIO panel, lowered hand, and Android-only compact discard selection are locked')
