import fs from 'node:fs'
const app = fs.readFileSync('src/App.tsx','utf8')
const audio = fs.readFileSync('src/audio.ts','utf8')
const assets = fs.readFileSync('src/audio-assets.ts','utf8')
const css = fs.readFileSync('src/V24.css','utf8') + '\n' + fs.readFileSync('src/Online.css','utf8')
const pkg = JSON.parse(fs.readFileSync('package.json','utf8'))
const must = (ok,msg) => { if (!ok) throw new Error(msg) }

must(pkg.scripts.build.includes('patch-production-jank-hotfix.mjs'), 'production jank hotfix is not in the build chain')
must(assets.includes('sfx-select.ogg'), 'card selection is not using the card-game reference sound')
must(assets.includes('sfx-card-draw.ogg'), 'draw is not using the card-game draw sound')
must(assets.includes('sfx-card-play.ogg'), 'card entry is not using the card-game play sound')
must(app.includes("new CustomEvent('mega-x:motion'"), 'motion state does not dispatch gameplay audio events')
must(audio.includes('private onMotionSfx'), 'state-driven motion SFX handler is missing')
must(audio.includes("kind === 'DRAW'"), 'draw event is not wired from motion state')
must(audio.includes("kind === 'ENTER_VS' || kind === 'SUPPORT'"), 'entry event is not wired from motion state')
must(audio.includes("kind === 'DESTROY'"), 'destroy event is not wired from motion state')
must(audio.includes(".combat-screen-fx.stage-impact')) kind = 'attack'"), 'attack impact event SFX is not wired')
must(audio.includes('attack: 0.34'), 'attack SFX is not gain-limited')
must(audio.includes('destroy: 0.30'), 'destroy SFX is not gain-limited')
must(!css.includes('.mega-coin{will-change:transform!important;contain:layout paint style!important;transform:translateZ(0)}'), 'mobile transform override still kills the coin keyframes')
must(css.includes('/* Production coin hotfix */'), 'coin waiting-title mobile hotfix missing')
must(css.includes('/* Arena mobile audit pass */'), 'arena mobile layout audit CSS missing')
must(css.includes('body:has(.duel-shell) #mx-audio-controls'), 'arena audio controls are not forced compact')
must(app.includes('CONFIRM DISCARD'), 'Spudur discard confirmation UI missing')
must(app.includes('selectedDiscardIds'), 'Spudur discard selection state missing')
must(app.includes("pending.mode === 'EXACT' && selectedDiscardIds.length !== pending.count"), 'discard count is not validated before online confirmation')
console.log('PASS arena audit: coin motion, card-game SFX, state-driven draw, sane gains, compact UI, Spudur confirmation')
