import fs from 'node:fs'
const main = fs.readFileSync('src/main.tsx','utf8')
const audio = fs.readFileSync('src/audio.ts','utf8')
const assets = fs.readFileSync('src/audio-assets.ts','utf8')
const vercel = JSON.parse(fs.readFileSync('vercel.json','utf8'))
const must = (ok, msg) => { if (!ok) throw new Error(msg) }
must(main.includes("import './audio.ts'"), 'audio engine is not booted by the production entry point')
must(assets.includes("coinToss: '/audio/coin-toss/mega-x-coin-toss-v1.opus'"), 'coin toss asset path missing')
must(audio.includes("'coinToss'"), 'coin toss scene missing')
must(audio.includes('fadeOutMusic'), 'coin toss -> fight fade missing')
must(audio.includes("previous === 'coinToss' && next === 'match'"), 'fight transition fade gate missing')
must(audio.includes('COIN_TOSS_GAIN = 1.0'), 'VS intro music gain missing')
must(audio.includes('private unlock() {'), 'unlock method missing')
must(audio.includes('if (this.unlocked) return'), 'unlock must guard against repeat calls')
must(audio.includes('this.unlocked = true'), 'unlock must mark itself unlocked')
must(audio.includes('this.syncScene(true)'), 'first user gesture no longer starts the current scene audio')
must(audio.includes("document.addEventListener('pointerdown', () => this.unlock(), { once: true, capture: true })"), 'pointer gesture audio unlock hook missing')
must(audio.includes("document.addEventListener('keydown', () => this.unlock(), { once: true, capture: true })"), 'keyboard gesture audio unlock hook missing')
must(!audio.includes("this.preloadSfx('ready')"), 'legacy ready SFX preload still competes with scene music')
must(!audio.includes("this.playSfx('ready')"), 'legacy ready SFX still competes with scene music')
const coinCache = vercel.headers?.find((entry) => entry.source === '/audio/coin-toss/(.*)\\.opus')
must(Boolean(coinCache), 'coin toss immutable cache route missing')
must(coinCache.headers?.some((h) => h.key === 'Cache-Control' && h.value === 'public, max-age=31536000, immutable'), 'immutable cache policy missing')
console.log('PASS coin toss audio path, scene transition, unlock, and cache contract')
