import fs from 'node:fs'
const main = fs.readFileSync('src/main.tsx','utf8')
const audio = fs.readFileSync('src/audio.ts','utf8')
const assets = fs.readFileSync('src/audio-assets.ts','utf8')
const css = fs.readFileSync('src/V24.css','utf8')
const vercel = JSON.parse(fs.readFileSync('vercel.json','utf8'))
const must = (ok, msg) => { if (!ok) throw new Error(msg) }
must(main.includes("import './audio.ts'"), 'audio engine is not booted by the production entry point')
must(assets.includes("coinToss: '/audio/coin-toss/mega-x-coin-toss-v1.opus'"), 'coin toss asset path missing')
must(audio.includes("'coinToss'"), 'coin toss scene missing')
must(audio.includes('fadeOutMusic'), 'coin toss -> fight fade missing')
must(audio.includes("previous === 'coinToss' && next === 'match'"), 'fight transition fade gate missing')
must(audio.includes('COIN_TOSS_GAIN = 0.78'), 'coin toss loudness safety gain missing')
must(audio.includes('Spend the first mobile gesture on starting the current scene music'), 'first mobile gesture is not reserved for scene music startup')
must(!audio.includes("this.preloadSfx('ready')\n    this.playSfx('ready')\n    this.syncScene(true)"), 'ready SFX still competes with scene music on first mobile gesture')
must(css.includes('/* Mobile animation performance contract */'), 'mobile coin toss performance patch missing')
must(css.includes('.start-screen:before,.start-screen:after{display:none!important}'), 'large animated start-screen paint layers remain enabled on phone')
must(css.includes('animation:coinFlipMobile .9s linear infinite!important'), 'phone coin animation is not using the low-paint path')
const coinCache = vercel.headers?.find((entry) => entry.source === '/audio/coin-toss/(.*)\\.opus')
must(Boolean(coinCache), 'coin toss immutable cache route missing')
must(coinCache.headers?.some((h) => h.key === 'Cache-Control' && h.value === 'public, max-age=31536000, immutable'), 'immutable cache policy missing')
console.log('PASS production boots mobile coin audio and uses low-paint coin animation')
