import fs from 'node:fs'
const app = fs.readFileSync('src/App.tsx','utf8')
const css = fs.readFileSync('src/arena-stage.css','utf8')
const runtime = fs.readFileSync('src/arena-stage.ts','utf8')
const start = app.indexOf('<div className="discard-card-grid">')
const end = app.indexOf('</div>', start)
if (start < 0 || end < 0) throw new Error('discard grid missing')
const section = app.slice(start, end)
if (!section.includes('className="discard-card-art"')) throw new Error('discard cards are not rendered directly')
if (section.includes('<CardView card={card} />')) throw new Error('discard cards still use shared CardView renderer')
if (!css.includes('Android discard direct-art authority')) throw new Error('direct discard art CSS authority missing')
if (!css.includes('grid-template-columns:repeat(2,minmax(0,1fr))')) throw new Error('discard grid is not two columns')
if (!css.includes('>.discard-card-art{position:relative!important;inset:auto!important')) throw new Error('discard art does not participate in natural card height')
if (!css.includes('aspect-ratio:auto!important')) throw new Error('discard card button still forces a fixed ratio')
if (!css.includes('pointer-events:none!important')) throw new Error('discard child layers may intercept taps')
if (!runtime.includes('function enforceMobileDiscardVisibility(')) throw new Error('mobile discard runtime visibility enforcement missing')
if (!runtime.includes("querySelectorAll<HTMLElement>('.discard-card-choice')")) throw new Error('discard buttons are not runtime-normalized')
if (!runtime.includes("querySelectorAll<HTMLImageElement>('.discard-card-choice img')")) throw new Error('discard images are not runtime-normalized')
if (!runtime.includes("style.setProperty('grid-template-columns', 'repeat(2,minmax(0,1fr))', 'important')")) throw new Error('discard runtime grid is not two columns')
if (!runtime.includes("button.style.setProperty('aspect-ratio', 'auto', 'important')")) throw new Error('runtime still forces discard button aspect ratio')
if (!runtime.includes("image.style.setProperty('position', 'relative', 'important')")) throw new Error('runtime still absolutely positions discard artwork')
if (!runtime.includes("image.style.setProperty('height', 'auto', 'important')")) throw new Error('runtime still forces discard artwork height')
if (!runtime.includes("button.style.setProperty('pointer-events', 'auto', 'important')")) throw new Error('discard buttons do not own pointer input')
if (!runtime.includes("image.style.setProperty('pointer-events', 'none', 'important')")) throw new Error('discard artwork can intercept pointer input')
if (!runtime.includes('enforceMobileDiscardVisibility()')) throw new Error('discard runtime enforcement is not mounted')
console.log('PASS discard cards render naturally in two columns and button owns tap input')
