import fs from 'node:fs'
const app = fs.readFileSync('src/App.tsx','utf8')
const css = fs.readFileSync('src/arena-stage.css','utf8')
const runtime = fs.readFileSync('src/arena-stage.ts','utf8')
const start = app.indexOf('<div className="discard-card-grid">')
const end = app.indexOf('</div>', start)
if (start < 0 || end < 0) throw new Error('discard grid missing')
const section = app.slice(start, end)
if (!section.includes('className="discard-card-art"')) throw new Error('discard cards are not rendered directly')
if (section.includes('<CardView card={card} />')) throw new Error('discard cards still use shared CardView renderer')
if (!css.includes('Android discard direct-art authority')) throw new Error('direct discard art CSS authority missing')
if (!css.includes('>.discard-card-art{position:absolute!important;inset:0!important')) throw new Error('discard art is not hard-pinned to its button')
if (!runtime.includes('function enforceMobileDiscardVisibility(')) throw new Error('mobile discard runtime visibility enforcement missing')
if (!runtime.includes("querySelectorAll<HTMLElement>('.discard-card-choice')")) throw new Error('discard buttons are not runtime-normalized')
if (!runtime.includes("querySelectorAll<HTMLImageElement>('.discard-card-choice img')")) throw new Error('discard images are not runtime-normalized')
if (!runtime.includes("style.setProperty('opacity', '1', 'important')")) throw new Error('discard image opacity is not forced visible at runtime')
if (!runtime.includes("style.setProperty('visibility', 'visible', 'important')")) throw new Error('discard image visibility is not forced at runtime')
if (!runtime.includes("style.setProperty('grid-template-columns', 'repeat(3,minmax(0,1fr))', 'important')")) throw new Error('discard grid is not runtime-normalized')
if (!runtime.includes('enforceMobileDiscardVisibility()')) throw new Error('discard runtime enforcement is not mounted')
console.log('PASS discard cards bypass shared CSS and receive runtime visibility enforcement')
