import { expect, type Page } from 'playwright/test'

export const COMMAND_WAIT_MS=8_000

type PointerTarget={key:string;kind:'HAND_CARD'|'TIE_CARD'|'BOARD_CARD'|'SELF_DISCARD_CARD'|'ACTION';action:string;label:string;x:number;y:number;cardId?:number;position?:'ATK'|'DEF';slot?:number}
type BoardBox={name:string;allow:string;left:number;top:number;right:number;bottom:number}
export type ArenaStatus={text:string;mode:'PRACTICE'|'ONLINE'|'LOADING';version:number;round:number;phase:'LOADING'|'SET_VS'|'EFFECT'|'ATTACK'|'TIE_BREAKER'|'GAME_OVER';position:string;legalActions:string[];connectionStatus:string;networkBusy:boolean;pointerTargetVersion:number;pointerTargets:PointerTarget[];selfDiscardMode:''|'EXACT'|'ANY';selfDiscardCount:number;selfDiscardLimit:number;selfDiscardSelected:number}
function parseTargets(raw:string|null):PointerTarget[]{if(!raw)return [];try{const value=JSON.parse(raw);if(!Array.isArray(value))return [];return value.filter((target):target is PointerTarget=>Boolean(target&&typeof target==='object'&&typeof target.action==='string'&&Number.isFinite(target.x)&&Number.isFinite(target.y)))}catch{return []}}
export async function assertNoArenaBoardOverlaps(page:Page,label:string){const viewport=page.viewportSize();if(!viewport||viewport.width!==390||viewport.height!==844)return;if(await page.locator('[data-arena-chrome="true"]').count()===0)return;const boxes=await page.locator('[data-board-element]').evaluateAll((elements)=>elements.flatMap((element)=>{const node=element as HTMLElement;const style=getComputedStyle(node);const rect=node.getBoundingClientRect();if(style.display==='none'||style.visibility==='hidden'||rect.width<1||rect.height<1)return [];return [{name:node.dataset.boardElement??node.className,allow:node.dataset.boardAllowOverlap??'',left:rect.left,top:rect.top,right:rect.right,bottom:rect.bottom}]})) as BoardBox[];expect(boxes.length,`${label}: board geometry probes missing`).toBeGreaterThan(10);const overlaps:string[]=[];for(let aIndex=0;aIndex<boxes.length;aIndex+=1){for(let bIndex=aIndex+1;bIndex<boxes.length;bIndex+=1){const a=boxes[aIndex];const b=boxes[bIndex];if(a.allow==='timer'||b.allow==='timer')continue;const overlapWidth=Math.min(a.right,b.right)-Math.max(a.left,b.left);const overlapHeight=Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top);if(overlapWidth>0.5&&overlapHeight>0.5)overlaps.push(`${a.name} x ${b.name} (${overlapWidth.toFixed(1)}×${overlapHeight.toFixed(1)})`)}}expect(overlaps,`${label}: unexpected board overlaps`).toEqual([])}
export async function arenaStatus(page:Page):Promise<ArenaStatus>{const locator=page.locator('[data-arena-status="true"]').first();const snapshot=await locator.evaluate((element)=>({mode:element.getAttribute('data-arena-mode')??'LOADING',version:Number(element.getAttribute('data-arena-version')??'-1'),round:Number(element.getAttribute('data-arena-round')??'0'),phase:element.getAttribute('data-arena-phase')??'LOADING',error:element.getAttribute('data-arena-error')??'',position:element.getAttribute('data-local-vs-position')??'',legalActions:(element.getAttribute('data-local-legal-actions')??'').split(',').filter(Boolean),connectionStatus:element.getAttribute('data-connection-status')??'',networkBusy:element.getAttribute('data-network-busy')==='true',pointerTargetVersion:Number(element.getAttribute('data-legal-target-version')??'-1'),pointerTargets:element.getAttribute('data-legal-targets'),selfDiscardMode:element.getAttribute('data-self-discard-mode')??'',selfDiscardCount:Number(element.getAttribute('data-self-discard-count')??'0'),selfDiscardLimit:Number(element.getAttribute('data-self-discard-limit')??'0'),selfDiscardSelected:Number(element.getAttribute('data-self-discard-selected')??'0')}));const pointerTargets=parseTargets(snapshot.pointerTargets);const selfDiscardMode=snapshot.selfDiscardMode==='EXACT'||snapshot.selfDiscardMode==='ANY'?snapshot.selfDiscardMode:'';expect(snapshot.error,`arena status became an error: ${snapshot.error}`).toBe('');if(snapshot.mode==='LOADING'||snapshot.phase==='LOADING')return {text:'LOADING',mode:'LOADING',version:-1,round:0,phase:'LOADING',position:snapshot.position,legalActions:snapshot.legalActions,connectionStatus:snapshot.connectionStatus,networkBusy:snapshot.networkBusy,pointerTargetVersion:snapshot.pointerTargetVersion,pointerTargets,selfDiscardMode,selfDiscardCount:snapshot.selfDiscardCount,selfDiscardLimit:snapshot.selfDiscardLimit,selfDiscardSelected:snapshot.selfDiscardSelected};expect(['PRACTICE','ONLINE'],`invalid arena mode: ${snapshot.mode}`).toContain(snapshot.mode);expect(['SET_VS','EFFECT','ATTACK','TIE_BREAKER','GAME_OVER'],`invalid arena phase: ${snapshot.phase}`).toContain(snapshot.phase);const mode=snapshot.mode as 'PRACTICE'|'ONLINE';const phase=snapshot.phase as ArenaStatus['phase'];return {text:`${mode} · V${snapshot.version} · ROUND ${snapshot.round} · ${phase}`,mode,version:snapshot.version,round:snapshot.round,phase,position:snapshot.position,legalActions:snapshot.legalActions,connectionStatus:snapshot.connectionStatus,networkBusy:snapshot.networkBusy,pointerTargetVersion:snapshot.pointerTargetVersion,pointerTargets,selfDiscardMode,selfDiscardCount:snapshot.selfDiscardCount,selfDiscardLimit:snapshot.selfDiscardLimit,selfDiscardSelected:snapshot.selfDiscardSelected}}
async function arenaVersion(page:Page){const snapshot=await page.locator('[data-arena-status="true"]').first().evaluate((element)=>({version:Number(element.getAttribute('data-arena-version')??'-1'),phase:element.getAttribute('data-arena-phase')??'LOADING',error:element.getAttribute('data-arena-error')??''}));expect(snapshot.error,`arena status became an error: ${snapshot.error}`).toBe('');return snapshot.phase==='LOADING'?-1:snapshot.version}
export async function waitForVersionChange(page:Page,version:number,timeout=COMMAND_WAIT_MS){try{await expect.poll(()=>arenaVersion(page),{timeout,intervals:[50,75,100,200,400]}).not.toBe(version);return true}catch{return false}}
async function waitForSettledTargets(page:Page){await expect.poll(async()=>{const status=await arenaStatus(page);return status.pointerTargetVersion===status.version&&!status.networkBusy},{timeout:COMMAND_WAIT_MS,intervals:[50,75,100,200,400]}).toBe(true);return arenaStatus(page)}
export async function waitForArenaReady(page:Page,timeout=20_000){await expect(page.locator('#arena-next-runtime-host canvas')).toBeVisible({timeout});await expect.poll(async()=>(await arenaStatus(page)).phase,{timeout}).not.toBe('LOADING');const status=await arenaStatus(page);await expect.poll(async()=>(await arenaStatus(page)).pointerTargetVersion,{timeout}).toBe(status.version);return arenaStatus(page)}
async function clickTarget(page:Page,target:PointerTarget){await page.mouse.click(target.x,target.y)}
function chooseTarget(status:ArenaStatus){const targets=status.pointerTargets;if(status.legalActions.includes('RESOLVE_SELF_DISCARD'))return undefined;if(status.phase==='SET_VS'){const setVs=targets.filter(target=>target.action==='SET_VS');return setVs.find(target=>target.cardId!==26&&target.cardId!==30&&target.position==='ATK')??setVs.find(target=>target.cardId!==26&&target.cardId!==30)??setVs.find(target=>target.position==='ATK')??setVs[0]??targets.find(target=>target.action==='BEGIN_ROUND')}if(status.phase==='EFFECT'){return targets.find(target=>target.action==='PLAY_EFFECT'&&target.cardId===30)??targets.find(target=>target.action==='PLAY_EFFECT'&&target.cardId===26)??targets.find(target=>target.action==='END_EFFECT_TURN')??targets.find(target=>target.action==='BEGIN_ROUND')??targets.find(target=>!['PLAY_EFFECT','SWITCH_POSITION','SELECT_SELF_DISCARD','RESOLVE_SELF_DISCARD'].includes(target.action))}if(status.phase==='ATTACK'){if(status.position!=='DEF')return targets.find(target=>target.action==='ATTACK')??targets.find(target=>target.action==='PASS_ATTACK');return targets.find(target=>target.action==='PASS_ATTACK')}if(status.phase==='TIE_BREAKER')return targets.find(target=>target.action==='TIE_PICK');return targets.find(target=>target.action!=='SELECT_SELF_DISCARD'&&target.action!=='RESOLVE_SELF_DISCARD')}
export async function resolveSelfDiscard(page:Page,status:ArenaStatus){
  const selectable=status.pointerTargets.filter(target=>target.action==='SELECT_SELF_DISCARD')
  const required=status.selfDiscardMode==='EXACT'?status.selfDiscardCount:Math.min(1,selectable.length)
  if(required>selectable.length)return {advanced:false,action:'RESOLVE_SELF_DISCARD',selfDiscardMode:status.selfDiscardMode,selfDiscardCount:status.selfDiscardCount}
  const capture=status.mode==='PRACTICE'&&status.selfDiscardMode==='EXACT'&&status.selfDiscardCount===2
  const zonBefore=Number(await page.locator('.mx-arena-effect-row.is-own .mx-arena-side-zone strong').textContent().catch(()=>'-1'))
  const handBefore=await page.locator('[data-arena-hand-card="true"]').count()
  if(capture){await expect(page.locator('[data-self-discard-banner="true"]')).toContainText('BUANG 2 KAD KE ZON TEPI · 0/2');await page.screenshot({path:'e2e-artifacts/arena-board-v2/self-discard-banner.png',fullPage:true})}
  if(status.selfDiscardMode==='ANY'){await expect(page.locator('[data-self-discard-banner="true"]')).toContainText(`BUANG SEHINGGA ${status.selfDiscardLimit} KAD KE ZON TEPI`)}
  for(let index=0;index<required;index+=1){await clickTarget(page,selectable[index]);await expect.poll(async()=>(await arenaStatus(page)).selfDiscardSelected,{timeout:2_000}).toBe(index+1);if(capture)await page.screenshot({path:`e2e-artifacts/arena-board-v2/self-discard-${index+1}-of-2.png`,fullPage:true})}
  const confirm=page.locator('[data-self-discard-confirm="true"]');await expect(confirm).toBeEnabled({timeout:2_000});await confirm.click();const advanced=await waitForVersionChange(page,status.version)
  if(capture&&advanced){await expect(page.locator('.mx-arena-effect-row.is-own .mx-arena-side-zone strong')).toHaveText(String(zonBefore+2),{timeout:4_000});await expect(page.locator('[data-arena-hand-card="true"]')).toHaveCount(handBefore-2,{timeout:4_000});expect((await arenaStatus(page)).phase,'match must continue after Pipit discard').not.toBe('GAME_OVER');await page.screenshot({path:'e2e-artifacts/arena-board-v2/self-discard-confirmed.png',fullPage:true});console.log('[SELF_DISCARD_E2E] EXACT 2 visible React selection confirmed; 2 cards moved to Zon Tepi and match continued')}
  if(status.selfDiscardMode==='ANY'&&advanced)console.log(`[SELF_DISCARD_E2E] ANY visible React selection confirmed with ${required} card`)
  return {advanced,action:'RESOLVE_SELF_DISCARD',selfDiscardMode:status.selfDiscardMode,selfDiscardCount:status.selfDiscardCount}
}
async function playEffectThroughInspect(page:Page,target:PointerTarget,version:number){await clickTarget(page,target);await expect(page.locator('[data-arena-inspect="true"]')).toBeVisible({timeout:COMMAND_WAIT_MS});await page.locator('[data-arena-inspect-play="true"]').click();return {advanced:await waitForVersionChange(page,version),action:'PLAY_EFFECT'}}
export async function driveOneHumanAction(page:Page){const before=await arenaStatus(page);if(before.phase==='GAME_OVER')return {advanced:true,action:'GAME_OVER'};const settled=await waitForSettledTargets(page);if(settled.legalActions.includes('RESOLVE_SELF_DISCARD'))return resolveSelfDiscard(page,settled);const target=chooseTarget(settled);if(!target)return {advanced:false,action:'NO_EXACT_TARGET'};if(target.action==='PLAY_EFFECT')return playEffectThroughInspect(page,target,settled.version);await clickTarget(page,target);return {advanced:await waitForVersionChange(page,settled.version),action:target.action}}
