import ReactDOM from 'react-dom/client'
import './index.css'
import './audio.ts'
import './landing-ui.ts'
import './landing-activation-fix.ts'
import './landing-polish.css'
import './lobby-ui.ts'
import App from './App.tsx'
import './arena-stage.css'
import './arena-premium.css'
import './arena-mobile-priority.css'
import './arena-usability.css'
import './arena-player-role.css'
import './arena-stage.ts'
import './arena-usability.ts'
import './arena-player-role.ts'
import './phaser-arena-loader.ts'
import './phaser-arena.css'
import './arena-art-assets.css'
import './arena-player-facing.css'
import './lobby-final.css'
import './lobby-last-fixes.ts'
import './lobby-last-fixes.css'
import './landing-bg-force.css'
import './landing-background-fallback.css'
import './landing-background-visible.css'
import './landing-cta-fighting.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <App />,
)
